const data = [
  {
    id: 1,
    itemPrincipal: ["Photosnap", "New!", "Featured"],
    profesion: "Senior Frontend Developer",
    fecha: "1d ago",
    time: "Full Time",
    localidad: "USA only",
    role: "Frontend",
    level: "Senior",
    lenguajes: ["HTML", "CSS", "JavaScript"],
    image:"https://res.cloudinary.com/dxvzsg7fa/image/upload/v1650232102/bookmark/sprint-2-reto-1/photosnap_jbaowb.svg"
  },
  {
    id: 2,
    itemPrincipal: ["Manage", "New!", "Featured"],
    profesion: "Fullstack Developer",
    fecha: "1d ago",
    time: "Part Time",
    localidad: "Remote",
    role: "Fullstack",
    level: "Midweight",
    lenguajes: ["Python"],
    tools: ["React"],
    image:"https://res.cloudinary.com/dxvzsg7fa/image/upload/v1650232102/bookmark/sprint-2-reto-1/manage_ovujs5.svg"

  },
  {
    id: 3,
    itemPrincipal: ["Account", "New!"],
    profesion: "Junior Frontend Developer",
    fecha: "2d ago",
    time: "Part Time",
    localidad: "USA only",
    role: "Frontend",
    level: "Junior",
    lenguajes: ["JavaScript"],
    tools: ["React", "Sass"],
    image:"https://res.cloudinary.com/dxvzsg7fa/image/upload/v1650232100/bookmark/sprint-2-reto-1/account_u9g4x4.svg"
  },
  {
    id: 4,
    itemPrincipal: ["MyHome"],
    profesion: "Junior Frontend Developer",
    fecha: "5d ago",
    time: "Contract",
    localidad: "USA only",
    role: "Frontend",
    level: "Junior",
    lenguajes: ["CSS", "JavaScript"],
    image:"https://res.cloudinary.com/dxvzsg7fa/image/upload/v1650232102/bookmark/sprint-2-reto-1/myhome_rm2za0.svg"
  },
  {
    id: 5,
    itemPrincipal: ["Loop Studios"],
    profesion: "Software Engineer",
    fecha: "1w ago",
    time: "Full Time",
    localidad: "Worldwide",
    role: "Fullstack",
    level: "Midweight",
    lenguajes: ["Ruby", "JavaScript"],
    tools: ["Sass"],
    image:"https://res.cloudinary.com/dxvzsg7fa/image/upload/v1650232101/bookmark/sprint-2-reto-1/loop-studios_bl36tq.svg"
  },
  {
    id: 6,
    itemPrincipal: ["FaceIt"],
    profesion: "Junior Backend Developer",
    fecha: "2w ago",
    time: "Full Time",
    localidad: "UK only",
    role: "Backend",
    level: "Junior",
    lenguajes: ["Ruby"],
    tools: ["RoR"],
    image:"https://res.cloudinary.com/dxvzsg7fa/image/upload/v1650232100/bookmark/sprint-2-reto-1/faceit_liqrww.svg"
  },
  {
    id: 7,
    itemPrincipal: ["Shortly"],
    profesion: "Junior Developer",
    fecha: "2w ago",
    time: "Full Time",
    localidad: "Worldwide",
    role: "Frontend",
    level: "Junior",
    lenguajes: ["HTML", "JavaScript"],
    tools: ["Sass"],
    image:"https://res.cloudinary.com/dxvzsg7fa/image/upload/v1650232102/bookmark/sprint-2-reto-1/shortly_gxzzxm.svg"
  },
  {
    id: 8,
    itemPrincipal: ["Insure"],
    profesion: "Junior Frontend Developer",
    fecha: "2w ago",
    time: "Full Time",
    localidad: "USA only",
    role: "Frontend",
    level: "Junior",
    lenguajes: ["JavaScript"],
    tools: ["Vue", "Sass"],
    image:"https://res.cloudinary.com/dxvzsg7fa/image/upload/v1650232102/bookmark/sprint-2-reto-1/insure_en1twh.svg"
  },
  {
    id: 9,
    itemPrincipal: ["Eyecam Co."],
    profesion: "Full Stack Engineer",
    fecha: "3w ago",
    time: "Worldwide",
    localidad: "USA only",
    role: "Fullstack",
    level: "Midweight",
    lenguajes: ["JavaScript", "Python"],
    tools:["Django"],
    image:"https://res.cloudinary.com/dxvzsg7fa/image/upload/v1650232100/bookmark/sprint-2-reto-1/eyecam-co_ujt0vb.svg"
  },
  {
    id: 10,
    itemPrincipal: ["The Air Filter Company"],
    profesion: "Front-end Dev",
    fecha: "1mo ago",
    time: "Part Time",
    localidad: " Worldwide",
    role: "Frontend",
    level: "Junior",
    lenguajes: ["JavaScript"],
    tools: ["React", "Sass"],
    image:"https://res.cloudinary.com/dxvzsg7fa/image/upload/v1650232103/bookmark/sprint-2-reto-1/the-air-filter-company_juidwf.svg"
  },
];
export { data };
